# Generated by Django 4.2.5 on 2023-09-20 08:36

import booksapp.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2)])),
                ('lastname', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2)])),
                ('birth', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['lastname', 'firstname'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
            options={
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=13, validators=[booksapp.models.validate_digits_length], verbose_name='ISBN number')),
                ('number_of_pages', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2)])),
                ('description', models.TextField(blank=True, null=True)),
                ('book_published_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), booksapp.models.max_value_current_year])),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booksapp.author')),
                ('book_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booksapp.language')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='author',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booksapp.country'),
        ),
    ]
